name    'adamjlow-proftpd'
version '0.0.1'
source 'git://github.com/adamjlow/adamjlow-proftpd.git'
author 'Adam J. Low'
license 'Apache License, Version 2.0'
summary 'Puppet module for managing ProFTPd'
description 'A comprehensive Puppet module for managing ProFTPd'
project_page 'http://github.com/adamjlow/adamjlow-proftpd'

dependency 'puppetlabs/stdlib', '>= 1.0.0'
